"""Turns the chosen Commons candidates into web images + credits.
Usage: python3 tools/process-images.py <round1-dir> [<round2-dir>]
Writes assets/img/<id>.jpg (max 800x600, progressive JPEG) and src/media.js (credits + focus points)."""
import json, sys, re, os
from PIL import Image
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
picks = {k: v for k, v in json.load(open(os.path.join(root, 'tools/image-picks.json'))).items() if not k.startswith('_')}
rounds = {1: sys.argv[1]}
if len(sys.argv) > 2: rounds[2] = sys.argv[2]
index = {r: {(e['id'], e['n']): e for e in json.load(open(os.path.join(d, 'index.json')))} for r, d in rounds.items()}

def tidy_artist(a):
    a = re.sub(r'\s+', ' ', a or '').strip()
    a = re.sub(r'^(Unknown author|Unknown|Anonymous|unknown)\b.*', '', a, flags=re.I)
    a = re.sub(r'\b(Creator|Author|Photographer):\s*', '', a)
    a = re.split(r'\s*(?:\(|; | - |, (?:uploaded|cropped|edited)|\bderivative work\b)', a)[0].strip(' ,.')
    return a[:48]

media = {}
for lane_id, p in picks.items():
    e = index[p.get('round', 1)][(p['src'], p['n'])]
    src = os.path.join(rounds[p.get('round', 1)], 'img', e['name'])
    im = Image.open(src).convert('RGB')
    im.thumbnail((800, 600), Image.LANCZOS)
    out = os.path.join(root, 'assets/img', f'{lane_id}.jpg')
    im.save(out, 'JPEG', quality=72, optimize=True, progressive=True)
    lic = e['license'] or 'see source'
    lic = 'Public domain' if lic.lower().startswith('public domain') or lic.upper() in ('PD', 'CC0', 'NO RESTRICTIONS') else lic
    artist = p['artist'] if 'artist' in p else tidy_artist(e['artist'])
    media[lane_id] = {
        'w': im.width, 'h': im.height, 'focus': p['focus'],
        'artist': artist, 'license': lic, 'licenseUrl': e.get('licenseUrl', ''),
        'source': e['page'], 'file': e['file'], 'date': e.get('date', '')[:40],
    }
    print(f"{lane_id}: {im.width}x{im.height} {os.path.getsize(out)//1024}KB | {artist or '—'} · {lic}")
js = '// Generated by tools/process-images.py: image size, focus point and attribution per scene lane.\nconst MEDIA = ' + json.dumps(media, ensure_ascii=False, indent=0).replace('\n', '') + ';\n'
open(os.path.join(root, 'src/media.js'), 'w').write(js)
print(len(media), 'images,', sum(os.path.getsize(os.path.join(root, 'assets/img', f)) for f in os.listdir(os.path.join(root, 'assets/img'))) // 1024, 'KB total')
